[package]
name = "ye"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.137"
nix = "0.25.0"
clap = { version = "4.0.18", features = ["derive"] }
